### ISSUE TITLE
Connect with internal address

### ISSUE THREAD

**Issue by hugeice** [InCar/ali-mqs#3]
现在使用的是MQS的公网地址来访问，如果ECS位于Aliyun内网，并且没有分配公网IP（选择公网带宽为0），则无法连接MQS。

**Comment by AceBear** [comment]
非常感谢提供反馈.

```Javascript
var AliMQS = require("ali-mqs");
var account = new AliMQS.Account("<your-owner-id>", "<your-key-id>", "<your-key-secret>");
var mq = new AliMQS.MQ("<your-mq-name>", account, "hangzhou-internal");
// send message
mq.sendP("Hello ali-mqs").then(console.log, console.error);
```

你能尝试一下,AliMQS.MQ时,指定region参数为内网形式,如 hangzhou -> hangzhou-internal 吗?
内网地址分别对应关系:
hangzhou -> hangzhou-internal
beijing -> beijing-internal
qingdao -> qingdao-internal

**Comment by hugeice** [comment]
'beijing-internal'方式测试可行，速度上也更快一些。谢谢！

**Comment by AceBear** [comment]
更新了一下readme, 明确了region参数可以使用internal形式的地址.
